# Generated by Django 2.2.1 on 2019-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraped_suits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suit',
            name='id',
        ),
        migrations.AlterField(
            model_name='suit',
            name='url',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
