# Generated by Django 2.2.1 on 2020-02-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraped_suits', '0003_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suit',
            options={'ordering': ['name'], 'verbose_name': 'Suit scraped from website'},
        ),
    ]
