#!/bin/sh

# modify prompt to let the user know that he can jam
PS1="\[\e[1;35m\](${PWD##*/})\[\e[0m\] $PS1"

run() {
    # ensure that quotes surrounding arguments are maintained
    # e.g. run web python manage.py run_sql "select 1"
    local args="";
    for i in "${@:3}"; do
        args=$args'"'$i'" '
    done

    local cmd="$2 $args"
    local docker_compose_service="$1"
    local execute_in_bash=""

    case "$docker_compose_service" in
    "web")  execute_in_bash="bash -c" ;;
    *)      execute_in_bash="" ;;
    esac

    docker-compose exec $docker_compose_service $execute_in_bash "$cmd"
}

# aliases can't be exported. Use functions instead
python()       { run web python "$@"; }
pip()          { run web pip "$@"; }
psql()         { docker-compose exec db psql "$@"; }
djangoadmin()  { run web django-admin "$@"; }

export -f python
export -f pip
export -f psql
export -f djangoadmin
